import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import MainNav from "@/component/MainNav";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
